services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: myjenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    restart: unless-stopped
    env_file:
      - .env
      
volumes:
  jenkins_data: